const productTechDataById = {
  1: [
    {
      model: "WP 250 (2.5 HP)",
      details: [
        { label: "Base Plate Diameter", value: '18" - 2.5 hp' },
        { label: "Power", value: "1850 W" },
        { label: "Voltage", value: "220 V" },
        { label: "Speed", value: "175 rpm" },
        { label: "Main Cable Length", value: "12 mtr" },
        { label: "Weight", value: "68 kgs" },
      ],
    },
    {
      model: "WP 300 (3.0 HP)",
      details: [
        { label: "Base Plate Diameter", value: '20" - 3 hp' },
        { label: "Power", value: "2250 W" },
        { label: "Voltage", value: "220 V" },
        { label: "Speed", value: "175 rpm" },
        { label: "Main Cable Length", value: "12 mtr" },
        { label: "Weight", value: "80 kgs" },
      ],
    },
  ],
  2: [
    {
      model: "WSD 1100 / WSD 1500",
      details: [
        { label: "Voltage", value: "220 V" },
        { label: "Power", value: "1100 W / 1500 W" },
        { label: "Speed", value: "154 RPM / Min" },
        { label: "Cable Length", value: "12 mtr" },
        { label: "Base Plate Diameter", value: '17" Inch' },
        { label: "Net Weight", value: "48 kg" },
        { label: "Handle Packing Size", value: "375*126*113 mm" },
        { label: "Main Body Packing Size", value: "540*440*365 mm" },
      ],
    },
  ],
  3: [
    {
      model: "WSD 1100 / WSD 1500",
      details: [
        { label: "Voltage", value: "220 V" },
        { label: "Power", value: "1100 W / 1500 W" },
        { label: "Speed", value: "154 RPM / Min" },
        { label: "Cable Length", value: "12 mtr" },
        { label: "Base Plate Diameter", value: '17" Inch' },
        { label: "Net Weight", value: "48 kg" },
        { label: "Handle Packing Size", value: "375*126*113 mm" },
        { label: "Main Body Packing Size", value: "540*440*365 mm" },
      ],
    },
  ],
  4: [
    {
      model: "WD-15C",
      details: [
        { label: "Operating Voltage", value: "220V" },
        { label: "Work Efficiency", value: "1500M²/H" },
        { label: "Brush", value: "350mm" },
        { label: "Brush Speed", value: "140RPM" },
        { label: "Solution Tank Capacity", value: "12L" },
        { label: "Recycling Bin Capacity", value: "15L" },
        { label: "Cable", value: "15 meters cable" },
        { label: "Product Size", value: "450*400*850mm" },
        { label: "Package Size", value: "510*485*90mm" },
        { label: "Water Absorption Width", value: "420mm" },
        { label: "Noise", value: "70db" },
        { label: "Brush Motor", value: "550W" },
        { label: "Product Weight", value: "30kg" },
      ],
    },
  ],
  5: [
    {
      model: "WD-25C",
      details: [
        { label: "Voltage", value: "220V" },
        { label: "Cleaning Width", value: "430mm" },
        { label: "Water Sucker Width", value: "530mm" },
        { label: "Water Sucking Motor", value: "700W" },
        { label: "Floor Motor Power", value: "750W" },
        { label: "Brush Rotation Speed", value: "140rpm" },
        { label: "Cleaning Rate", value: "1700M²/h" },
        { label: "Clean Water Tank Capacity", value: "25Liter" },
        { label: "Dirty Water Tank Capacity", value: "25Liter" },
        { label: "Cable", value: "18m" },
      ],
    },
  ],
  6: [
    {
      model: "WD-30C",
      details: [
        { label: "Voltage Frequency", value: "230v/50Hz" },
        { label: "Water Sucker", value: "855 mm" },
        { label: "Brush Diameter", value: "550mm" },
        { label: "Rolling Brush Motor", value: "1000 W" },
        { label: "Water Sucking Motor", value: "1000 W" },
        { label: "Brush Rotation Speed", value: "154 RPM/MIN" },
        { label: "Cleaning Width", value: "550 mm" },
        { label: "Cleaning Rate", value: "1680 sqmtr/Hr" },
        { label: "Brush Pressure", value: "40 Kg" },
        { label: "Clean Water Tank", value: "30 L" },
        { label: "Dirty Water Tank", value: "35 L" },
        { label: "Cable", value: "18 M" },
        { label: "Net Weight", value: "75.6 Kg" },
        { label: "Gross Weight", value: "98.54 Kg" },
        { label: "Dimensions", value: "965x615x1020 mm" },
        { label: "Color", value: "Blue | Grey" },
      ],
    },
  ],
  7: [
    {
      model: "WD-40C and WD-40B",
      details: [
        { label: "L X W X H", value: "1000x500x1000mm" },
        { label: "Machine Only", value: "85 kg" },
        { label: "Working Efficiency", value: "1870 m²/h" },
        { label: "Max. Gradeability", value: "10°" },
        { label: "Squeegee Width", value: "720 mm" },
        { label: "Brush Width", value: "460 mm" },
        { label: "Turning Radius", value: "500 mm" },
        { label: "Suction Motor", value: "450 W" },
        { label: "Brush Motor", value: "380 W" },
        { label: "Battery", value: "DC 12V/80Ah" },
        { label: "Working Time", value: "2-3 h" },
        { label: "Charging Time", value: "3-6 h" },
        { label: "Clean Water Tank Capacity", value: "36 L" },
        { label: "Sewage Tank Capacity", value: "40 L" },
        { label: "Noise Level", value: "60 dB" },
      ],
    },
  ],
  8: [
    {
      model: "WD-50C and WD-50B",
      details: [
        { label: "Vacuum Motor W (hp)", value: "600W (0.8hp)" },
        { label: "Brush Motor W (hp)", value: "550W (0.74hp)" },
        { label: "Min. Aisle Turn mm", value: "650mm" },
        { label: "Cleaning Path mm", value: '490mm/18"' },
        { label: "Squeegee Width mm", value: "830mm" },
        { label: "Max. Coverage Per Hr", value: "1750 m²/h" },
        { label: "Solution Tank Capacity", value: "50 L" },
        { label: "Recovery Tank Capacity", value: "55 L" },
        { label: "Continuous Operating Time", value: "3-4h" },
        { label: "Charging Time", value: "6-8h" },
        { label: "Operating Weight", value: "136 kg" },
        { label: "Operating Size", value: "1220 x 830 x 950 mm" },
        { label: "Packing", value: "Wood Pallet + Carton" },
      ],
    },
    {
      model: "WD-50 B (Battery Operated)",
      details: [
        { label: "Battery", value: "24V/100Ah" },
        { label: "Vacuum Motor W (hp)", value: "450W(0.6hp)" },
        { label: "Brush Motor W (hp)", value: "550W(0.74hp)" },
        { label: "Min. Aisle Turn mm", value: "650mm" },
        { label: "Cleaning Path mm", value: '490mm/18"' },
        { label: "Squeegee Width mm", value: "830mm" },
        { label: "Max. Coverage Per Hr", value: "2350 m²/h" },
        { label: "Solution Tank Capacity", value: "50 L" },
        { label: "Recovery Tank Capacity", value: "55 L" },
        { label: "Continuous Operating Time", value: "3-4h" },
        { label: "Charging Time", value: "6-8h" },
        { label: "Operating Weight (Battery)", value: "158 kg" },
        { label: "Operating Size", value: "1220 x 830 x 950 mm" },
        { label: "Packing", value: "Wood Pallet + Carton" },
      ],
    },
  ],
  9: [
    {
      model: "WD-60",
      details: [
        { label: "Cleaning Width", value: "500 mm" },
        { label: "Squeegee Width", value: "825 mm" },
        { label: "Continuous Running Time", value: "2-3 h" },
        { label: "Theoretical Cleaning Efficiency", value: "2800 m²/h" },
        { label: "Battery Capacity", value: "24V/100Ah" },
        { label: "Suction Motor Power", value: "500 W" },
        { label: "Brush Motor Power", value: "550 W" },
        { label: "Driving Motor Power", value: "550 W" },
        { label: "Solution Tank Capacity", value: "55 L" },
        { label: "Recovery Tank Capacity", value: "60 L" },
        { label: "Total Weight", value: "158 kg" },
        { label: "Product Size", value: "1200*825*1000 mm" },
      ],
    },
  ],
  10: [
    {
      model: "WD-70",
      details: [
        { label: "Battery (Free Maintenance)", value: "24v/100A" },
        { label: "Charger", value: "24v/15A" },
        { label: "Drive Motor W (HP)", value: "300W (0.4hp)" },
        { label: "Vacuum Motor W (HP)", value: "450W (0.6hp)" },
        { label: "Brush Motor W (HP)", value: "550W (0.74hp)" },
        { label: "Min. Aisle Turn (mm)", value: "700mm" },
        { label: "Cleaning Path mm (Brush Size Inch)", value: '510mm/19"' },
        { label: "Squeegee Width mm (inch)", value: "830mm" },
        { label: "Max. Coverage Per Hour (m³/h)", value: "2650 m³/h" },
        { label: "Gradeability %", value: "5%" },
        { label: "Solution Tank Capacity", value: "65L" },
        { label: "Recovery Tank Capacity (L)", value: "70L" },
        { label: "Continuous Operating Time (h)", value: "3-4h" },
        { label: "Charging Time (h)", value: "6-8h" },
        { label: "Operating Weight (inc. battery)", value: "151kg" },
        { label: "Operating Size mm", value: "1300*830*1125mm" },
        { label: "Packing", value: "Wood Pallet + Carton" },
      ],
    },
  ],
  11: [
    {
      model: "New Model",
      details: [
        { label: "Cleaning Width", value: "750 mm" },
        { label: "Squeegee Width", value: "1000 mm" },
        { label: "Continuous Running Hour", value: "3h" },
        { label: "Theoretical Working Efficiency", value: "5900 m²/h" },
        { label: "Battery Capacity", value: "24V/140Ah" },
        { label: "Suction Motor Power", value: "500W" },
        { label: "Brush Motor Power", value: "350*2W" },
        { label: "Driving Motor Power", value: "450W" },
        { label: "Clean Water Capacity", value: "80L" },
        { label: "Sewage Capacity", value: "85L" },
        { label: "Total Weight", value: "207.5 kg" },
        { label: "Working Size", value: "1400*1000*1100 mm" },
      ],
    },
  ],
  12: [
    {
      model: "New Model",
      details: [
        { label: "Cleaning Width (mm)", value: "800 mm" },
        { label: "Squeegee Width (mm)", value: "1200 mm" },
        { label: "Continuous Running Hour (h)", value: "3-5 h" },
        { label: "Theoretical Working Efficiency (m²/h)", value: "6800 m²/h" },
        { label: "Battery Capacity (V/Ah)", value: "24/200" },
        { label: "Suction Motor Power (W)", value: "600 W" },
        { label: "Brush Motor Power (W)", value: "350*2 W" },
        { label: "Driving Motor Power (W)", value: "600 W" },
        { label: "Clean Water Capacity (L)", value: "120 L" },
        { label: "Sewage Capacity (L)", value: "150 L" },
        { label: "Total Weight (kg)", value: "340 kg" },
        { label: "Working Size (mm)", value: "1600*1200*1300 mm" },
      ],
    },
  ],
  13: [
    {
      model: "WD-80DB",
      details: [
        { label: "Battery (Free Maintenance)", value: "24V/120A" },
        { label: "Charger", value: "24V/15A" },
        { label: "Drive Motor W (hp)", value: "400W (0.4hp)" },
        { label: "Vacuum Motor W (hp)", value: "450W (0.6hp)" },
        { label: "Brush Motor W (hp)", value: "400W (0.54hp)*2" },
        { label: "Min. Aisle Turn (mm)", value: "1150mm" },
        { label: 'Cleaning Path mm (Brush Size "inch)', value: '360mm/13"*2' },
        { label: 'Squeegee Width mm ("inch)', value: "920mm" },
        { label: "Max. Coverage per Hrs. (m²/h)", value: "4300 m²/h" },
        { label: "Gradeability %", value: "25%" },
        { label: "Solution Tank Capacity (L)", value: "75L" },
        { label: "Recovery Tank Capacity (L)", value: "80L" },
        { label: "Continuous Operating Time (h)", value: "3-4h" },
        { label: "Charging Time (h)", value: "6-8h" },
        { label: "Operating Weight (inc. battery)", value: "220kg" },
        { label: "Operating size mm", value: "1300*920*1140 mm" },
        { label: "Packing", value: "Metal pallet+frame+polywood" },
      ],
    },
  ],
  14: [
    {
      model: "WD-90DB",
      details: [
        { label: "Battery (Free Maintenance)", value: "24V/120A" },
        { label: "Charger", value: "24V/15A" },
        { label: "Drive Motor W (hp)", value: "400W (0.54hp)" },
        { label: "Vacuum Motor W (hp)", value: "500W (0.67hp)" },
        { label: "Brush Motor W (hp)", value: "400W (0.54hp) X 2" },
        { label: "Min. Aisle Turn (mm)", value: "1200mm" },
        {
          label: 'Cleaning Path mm (Brush Size "inch)',
          value: '360mm/13" X 2',
        },
        { label: 'Squeegee Width mm ("inch)', value: "920mm" },
        { label: "Max. Coverage per Hrs. (m²/h)", value: "4300 m²/h" },
        { label: "Gradeability %", value: "20%" },
        { label: "Solution Tank Capacity (L)", value: "90L" },
        { label: "Recovery Tank Capacity (L)", value: "100L" },
        { label: "Continuous Operating Time (h)", value: "3-4h" },
        { label: "Charging Time (h)", value: "6-8h" },
        { label: "Operating Weight (inc. battery)", value: "238kg" },
        { label: "Operating size mm", value: "1370 X 920 X 1230 mm" },
        { label: "Packing", value: "Metal Pallet + frame + Polywood" },
      ],
    },
  ],
  15: [
    {
      model: "WD-120DB",
      details: [
        { label: "Battery (Free Maintenance)", value: "24V/150AH" },
        { label: "Charger", value: "24V/20A" },
        { label: "Drive Motor W (hp)", value: "400W (0.54hp)" },
        { label: "Vacuum Motor W (hp)", value: "550W (0.74hp)" },
        { label: "Brush Motor W (hp)", value: "400W (0.54hp) X 2" },
        { label: "Min. Aisle Turn (mm)", value: "1300mm" },
        { label: 'Cleaning Path mm (Brush Size "inch)', value: "380mm/14 X 2" },
        { label: 'Squeegee Width mm ("inch)', value: "1000mm" },
        { label: "Max. Coverage per Hrs. (m²/h)", value: "4600 m²/h" },
        { label: "Gradeability %", value: "25%" },
        { label: "Solution Tank Capacity (L)", value: "110L" },
        { label: "Recovery Tank Capacity (L)", value: "120L" },
        { label: "Continuous Operating Time (h)", value: "3-4h" },
        { label: "Charging Time (h)", value: "6-8h" },
        { label: "Operating Weight (inc. battery)", value: "266Kg" },
        { label: "Operating size mm", value: "1430 X 1000 X 1280 mm" },
        { label: "Packing", value: "Metal Pallet + Frame + Polywood" },
      ],
    },
  ],
  16: [
    {
      model: "WD-180DB",
      details: [
        { label: "Battery (Free Maintenance)", value: "24V/200AH" },
        { label: "Charger", value: "24V/25A" },
        { label: "Drive Motor W (hp)", value: "650W (0.87hp)" },
        { label: "Vacuum Motor W (hp)", value: "600W (0.8hp)" },
        { label: "Brush Motor W (hp)", value: "550W (0.74hp)" },
        { label: "Min. Aisle Turn (mm)", value: "1300mm" },
        {
          label: 'Cleaning Path mm (Brush Size "inch)',
          value: '460mm/17" X 2',
        },
        { label: 'Squeegee Width mm ("inch)', value: "1200mm" },
        { label: "Max. Coverage per Hrs. (m²/h)", value: "6500 m²/h" },
        { label: "Gradeability %", value: "20%" },
        { label: "Solution Tank Capacity (L)", value: "160L" },
        { label: "Recovery Tank Capacity (L)", value: "180L" },
        { label: "Continuous Operating Time (h)", value: "3-4.5h" },
        { label: "Charging Time (h)", value: "6-8h" },
        { label: "Operating Weight (inc. battery)", value: "412kg" },
        { label: "Operating size mm", value: "1650 x 1200 x 1490 mm" },
        { label: "Packing", value: "Metal pallet + frame + polywood" },
      ],
    },
  ],
  17: [
    {
      model: "WS-1200",
      details: [
        { label: "Battery (Free Maintenance)", value: "48V/58Ah" },
        { label: "Charger", value: "24V/8A" },
        { label: "Drive Motor W", value: "800W" },
        { label: "Vacuum Motor W", value: "500W" },
        { label: "Cylindrical Brush Motor W", value: "750mm" },
        { label: "Side Brush Motor W", value: "90W X 2" },
        { label: "Min. Aisle Turn (mm)", value: "1500mm" },
        { label: "Cleaning Path (mm)", value: "1250" },
        { label: "Cylindrical Brush Width (mm)", value: "300*500mm" },
        { label: "Side Brush Width (mm)", value: "460 mm" },
        { label: "Max. Coverage per Hour (m²/h)", value: "7500" },
        { label: "Water Tank Capacity", value: "28L" },
        { label: "Debris Hopper Capacity", value: "85L" },
        { label: "Continuous Operating Time (h)", value: "2-3h" },
        { label: "Charging Time (h)", value: "8-10h" },
        { label: "Operating Weight (inc. Battery)", value: "339kg" },
        { label: "Operating Size (mm)", value: "1550 x 1250 x 1250" },
      ],
    },
  ],
  18: [
    {
      model: "WS-1400",
      details: [
        { label: "Cleaning Capacity", value: "9500 m²/h" },
        { label: "Sweeping Path", value: "1400 mm" },
        { label: "Side Brush", value: "2*500 mm" },
        { label: "Capacity of Dirt Container", value: "140 L" },
        { label: "Main Brush Motor", value: "500 W" },
        { label: "Fan Motor", value: "115 W" },
        { label: "Water Tank", value: "90 L" },
        { label: "Weight with Battery", value: "630 Kg" },
        { label: "Working Time", value: "6 Hrs." },
        { label: "Main Brush", value: "700 mm" },
        { label: "Battery", value: "48V/100AH" },
        { label: "Driving Motor", value: "1200 W" },
        { label: "Side Brush Motor", value: "2*90 W" },
        { label: "Filter", value: "7 m²" },
        { label: "Driving Speed", value: "0-8 km/h" },
        { label: "Size with Brushes (LWH)", value: "1615 x 1400 x 1560 mm" },
      ],
    },
  ],
  19: [
    {
      model: "WS-1400",
      details: [
        { label: "Battery (Free Maintenance)", value: "48V/80Ah" },
        { label: "Charger", value: "24V/15A" },
        { label: "Drive Motor W", value: "1000W" },
        { label: "Vacuum Motor W", value: "500W" },
        { label: "Cylindrical Brush Motor W", value: "850mm" },
        { label: "Side Brush Motor W", value: "90W * 2" },
        { label: "Min. Aisle Turn", value: "1500mm" },
        { label: "Cleaning Path", value: "1450 mm" },
        { label: "Cylindrical Brush Width", value: "300 * 700 mm" },
        { label: "Side Brush Width", value: "500 mm" },
        { label: "Max. Coverage Per Hour", value: "8700 m³/h" },
        { label: "Water Tank Capacity", value: "90L" },
        { label: "Debris Hopper Capacity", value: "150L" },
        { label: "Gradeability", value: "25%" },
        { label: "Charging Time", value: "8-10h" },
        { label: "Operating Weight (inc. battery)", value: "465kg" },
        {
          label: "Operating Size",
          value: "1700 x 1400 x 1250 mm (1700 x 1400 x 2050 mm Top Cover)",
        },
      ],
    },
  ],
  20: [
    {
      model: "WB 2500",
      details: [
        { label: "Cleaning Width", value: "2050 mm" },
        { label: "Rolling Brush Width", value: "800 mm" },
        { label: "Side Brush Width", value: "600 * 4 mm" },
        { label: "Continuous Running Time", value: "4-6 h" },
        { label: "Theoretical Cleaning Efficiency", value: "15000 m³/h" },
        { label: "Battery Capacity", value: "48V/150Ah" },
        { label: "Suction Motor Power", value: "500 * 2 W" },
        { label: "Rolling Brush Motor Power", value: "800 W" },
        { label: "Side Brush Motor Power", value: "90 * 4 W" },
        { label: "Driving Motor Power", value: "1800 W" },
        { label: "Debris Hopper Capacity", value: "200 L" },
        { label: "Water Tank Capacity", value: "150 L" },
        { label: "Total Weight", value: "990 kg" },
        { label: "Product Size", value: "2630 x 2050 x 2400 mm" },
      ],
    },
  ],
  21: [
    {
      model: "WS-3000",
      details: [
        { label: "Cleaning Width", value: "1900-2200 mm" },
        { label: "Rolling Brush Width", value: "690 mm" },
        { label: "Side Brush Width", value: "500 * 4 mm" },
        { label: "Continuous Running Time", value: "5 h" },
        { label: "Theoretical Cleaning Efficiency", value: "22000 m²/h" },
        { label: "Battery Capacity", value: "48V/300Ah" },
        { label: "Suction Motor Power", value: "500 * 2 W" },
        { label: "Rolling Brush Motor Power", value: "800 * 2 W" },
        { label: "Side Brush Motor Power", value: "90 * 4 W" },
        { label: "Driving Motor Power", value: "5000 W" },
        { label: "Debris Hopper Capacity", value: "240 L" },
        { label: "Water Tank Capacity", value: "200 L" },
        { label: "Total Weight", value: "1580 kg" },
        { label: "Product Size", value: "3950 x 2050 x 2000 mm" },
      ],
    },
  ],
  22: [
    {
      model: "WS2000A",
      details: [
        { label: "Cleaning Capacity", value: "12000 m²/h" },
        { label: "Sweeping Path", value: "2100 mm" },
        { label: "Side Brush", value: "4 * 500 mm" },
        { label: "Capacity of Dirt Container", value: "250 L" },
        { label: "Main Brush Motor", value: "1000 W" },
        { label: "Driving Speed", value: "0-8 km/h" },
        { label: "Fan Motor", value: "600 W * 2 pcs" },
        { label: "Filter", value: "15 m²" },
        { label: "Size With Brushes", value: "2200 x 2000 x 2100 mm" },
        { label: "Working Time", value: "6-8 hrs." },
        { label: "Main Brush", value: "800 mm" },
        { label: "Battery", value: "48V/150Ah" },
        { label: "Driving Motor", value: "1200 W" },
        { label: "Side Broom Quantity", value: "4 * 80 W" },
        { label: "Climbing Ability", value: "25 m*" },
        { label: "Water Spray", value: "Standard" },
        { label: "Water Container", value: "110 L" },
        { label: "Weight With Battery", value: "1050 kg" },
      ],
    },
  ],
  23: [
    {
      model: "ELECTRIC WALK BEHIND SWEEPER WS-45L", // Replace with the actual model name if available
      details: [
        { label: "Cleaning Capacity", value: "4800 m²/H" },
        { label: "Sweeping Path", value: "1060 mm" },
        { label: "Side Brush", value: "2 * 280 mm" },
        { label: "Capacity of Direct Container", value: "45 L" },
        { label: "Main Brush Motor", value: "300 W" },
        { label: "Fan", value: "50 W" },
        { label: "Dimension (LWH)", value: "1100 x 978 x 950 mm" },
        { label: "Working Time", value: "4-6 hrs" },
        { label: "Main Brush Width", value: "500 mm" },
        { label: "Battery", value: "48V / >20Ah" },
        { label: "Filter", value: "2.6 m²" },
        { label: "Side Broom Quantity", value: "2 * 90 W" },
        { label: "Water Container", value: "40 L (Optional)" },
        { label: "Weight With Battery", value: "95 kg" },
      ],
    },
  ],
  24: [
    {
      model: "MANUAL SWEEPER  MACHINE WS-920",
      details: [
        { label: "Cleaning Capacity", value: "3850 m²/h" },
        { label: "Sweeping Path", value: "920 mm" },
        { label: "Side Brush", value: "2 * 350 mm" },
        { label: "Capacity of Dirt Container", value: "50 L" },
        { label: "Main Brush Motor", value: "N/A" },
        { label: "Fan", value: "N/A" },
        { label: "Dimension (L x W x H)", value: "1250 x 920 x 1050 mm" },
        { label: "Main Brush Width", value: "800 mm" },
        { label: "Battery", value: "N/A" },
        { label: "Filter", value: "1.5 m²" },
        { label: "Side Broom Quantity", value: "N/A" },
        { label: "Water Container", value: "N/A" },
        { label: "Weight", value: "25 kg" },
      ],
    },
  ],
  25: [
    {
      model: "WCE-3035",
      details: [
        { label: "Voltage/Frequency", value: "220V/50Hz" },
        { label: "Power", value: "2320W" },
        { label: "Roll Brush Speed", value: "1400 rpm/min" },
        { label: "Roll Brush Motor", value: "220V/180W" },
        { label: "Roll Brush Width", value: "400 mm" },
        { label: "Water Sucking Motor", value: "220V/1000W" },
        { label: "Water Sucker Width", value: "460 mm" },
        { label: "Clean Water Tank Capacity", value: "30 L" },
        { label: "Dirty Water Tank Capacity", value: "35 L" },
        { label: "Cable Length", value: "18 m" },
        { label: "Net Weight", value: "46.2 kg" },
        { label: "Gross Weight", value: "65 kg" },
        { label: "Size", value: "1110 x 550 x 1050 mm" },
      ],
    },
  ],
  26: [
    {
      model: "ULTIMO 15",
      details: [
        { label: "Function", value: "Wet and Dry" },
        { label: "Capacity", value: "15 Liter" },
        { label: "Power", value: "1000 W" },
        { label: "Voltage", value: "220-240V" },
        { label: "Height", value: "55 CM" },
        { label: "Tank Diameter", value: "345 mm" },
        { label: "Air Flow", value: "48 L/S" },
        { label: "Vacuum Suction", value: "210 m/bar" },
        { label: "Cable Length", value: "7 M" },
        { label: "Hose Diameter", value: "36 mm" },
        { label: "Weight", value: "11.5 kg" },
      ],
    },
  ],
  27: [
    {
      model: "ULTIMO 30",
      details: [
        { label: "Function", value: "Wet and Dry" },
        { label: "Capacity", value: "30 Liter" },
        { label: "Power", value: "1000 W" },
        { label: "Voltage", value: "220-240V" },
        { label: "Height", value: "76 CM" },
        { label: "Tank Diameter", value: "345 mm" },
        { label: "Air Flow", value: "53 L/S" },
        { label: "Vacuum Suction", value: "230 m/bar" },
        { label: "Cable Length", value: "7 M" },
        { label: "Hose Diameter", value: "36 mm" },
        { label: "Weight", value: "13 kg" },
      ],
    },
  ],
  28: [
    {
      model: "ULTIMO 60",
      details: [
        { label: "Function", value: "Wet and Dry" },
        { label: "Capacity", value: "60 Liter" },
        { label: "Power", value: "2000 W" },
        { label: "Voltage", value: "220-240V" },
        { label: "Height", value: "90 CM" },
        { label: "Tank Diameter", value: "440 mm" },
        { label: "Air Flow", value: "48 L/S" },
        { label: "Vacuum Suction", value: "250 m/bar" },
        { label: "Cable Length", value: "8 M" },
        { label: "Hose Diameter", value: "40 mm" },
        { label: "Weight", value: "27 kg" },
      ],
    },
  ],
  29: [
    {
      model: "ULTIMO 80",
      details: [
        { label: "Function", value: "Wet and Dry" },
        { label: "Capacity", value: "80 Liter" },
        { label: "Power", value: "3000 W" },
        { label: "Voltage", value: "220-240V" },
        { label: "Height", value: "100 CM" },
        { label: "Tank Diameter", value: "440 mm" },
        { label: "Air Flow", value: "159 L/S" },
        { label: "Vacuum Suction", value: "250 m/bar" },
        { label: "Cable Length", value: "8 M" },
        { label: "Hose Diameter", value: "40 mm" },
        { label: "Weight", value: "30 kg" },
      ],
    },
  ],
  30: [
    {
      model: "WC 20",
      details: [
        { label: "Function", value: "Carpet Cleaner" },
        { label: "Capacity", value: "20 L" },
        { label: "Clean Water Capacity", value: "10 L" },
        { label: "Power", value: "1034 W" },
        { label: "Voltage", value: "220V-240V" },
        { label: "Height", value: "890 mm" },
        { label: "Air Flow Rate", value: "53 L/S" },
        { label: "Vacuum Suction", value: "230 mbar" },
        { label: "Length Of The Cable", value: "7 M" },
        { label: "Net Weight", value: "17.4 Kg" },
        { label: "Pressures", value: "87 PSI" },
        { label: "Grinding Head Voltage", value: "-" },
        { label: "Grinding Head Motor", value: "-" },
      ],
    },
  ],
  32: [
    {
      model: "WC 40",
      details: [
        { label: "Function", value: "Carpet Cleaner" },
        { label: "Capacity", value: "20 L" },
        { label: "Clean Water Capacity", value: "10 L" },
        { label: "Power", value: "1034 W" },
        { label: "Voltage", value: "220V-240V" },
        { label: "Height", value: "890 mm" },
        { label: "Air Flow Rate", value: "53 L/S" },
        { label: "Vacuum Suction", value: "230 mbar" },
        { label: "Length Of The Cable", value: "7 M" },
        { label: "Net Weight", value: "24.5 Kg" },
        { label: "Pressures", value: "87 PSI" },
        { label: "Grinding Head Voltage", value: "-" },
        { label: "Grinding Head Motor", value: "-" },
      ],
    },
  ],

  31: [
    {
      model: "WC 20SF",
      details: [
        { label: "Function", value: "Carpet Cleaner" },
        { label: "Capacity", value: "20 L" },
        { label: "Clean Water Capacity", value: "10 L" },
        { label: "Power", value: "1079 W" },
        { label: "Voltage", value: "220V" },
        { label: "Power Of Water Pump", value: "34 W" },
        { label: "Power Of Vacuum Motor", value: "1000 W" },
        { label: "Height", value: "890 mm" },
        { label: "Air Flow Rate", value: "53 L/S" },
        { label: "Vacuum Suction", value: "230 mbar" },
        { label: "Length Of The Cable", value: "7 M" },
        { label: "Net Weight", value: "28.5 Kg" },
        { label: "Pressures", value: "87 PSI" },
        { label: "Grinding Head Voltage", value: "12V" },
        { label: "Grinding Head Motor", value: "45 W" },
      ],
    },
  ],
  33: [
    {
      model: "WC 40SF",
      details: [
        { label: "Function", value: "Carpet Cleaner" },
        { label: "Capacity", value: "40 L" },
        { label: "Clean Water Capacity", value: "10 L" },
        { label: "Power", value: "1079 W" },
        { label: "Voltage", value: "220V" },
        { label: "Power Of Water Pump", value: "34 W" },
        { label: "Power Of Vacuum Motor", value: "1000 W" },
        { label: "Height", value: "890 mm" },
        { label: "Air Flow Rate", value: "53 L/S" },
        { label: "Vacuum Suction", value: "230 mbar" },
        { label: "Length Of The Cable", value: "7 M" },
        { label: "Net Weight", value: "32.5 Kg" },
        { label: "Pressures", value: "87 PSI" },
        { label: "Grinding Head Voltage", value: "12V" },
        { label: "Grinding Head Motor", value: "45 W" },
      ],
    },
  ],
};

export { productTechDataById };
